FROM ghcr.io/getsops/sops:v3.11.0

ENV SOPS_AGE_KEY_FILE=/app/age/key.txt

WORKDIR /app

COPY secrets.yml /app/secrets.yaml
# COPY .sops.yaml /app/.sops.yaml

RUN mkdir -p /app/secrets /app/age

# CMD ["--config", "/app/.sops.yaml", "-d", "--output", "/app/secrets/secrets.yaml", "/app/secrets.yaml"]
CMD ["-d", "--output", "/app/secrets/secrets.yaml", "/app/secrets.yaml"]
